export const LIST_USER = "LIST_USER";
export const USER_FETCH_REQUESTED = "USER_FETCH_REQUESTED";
export const USER_FETCH_SUCCEEDED = "USER_FETCH_SUCCEEDED"; 
export const USER_FETCH_FAILED =  "USER_FETCH_FAILED";
export const USER_ADD_SUCCEEDED = "USER_ADD_SUCCEEDED";
export const USER_ADD_FAILED = "USER_ADD_FAILED";
export const USER_ADD_REQUESTED = "USER_ADD_REQUESTED";